### ISSUE TITLE
Having trouble running on OSX

### ISSUE THREAD

**Issue by joeblew99** [gotoolkit/go-react-app#1]
i ran the docker compose up and got no errors.

But i think its looking for the wrong port ?
https://github.com/gotoolkit/go-react-app/blob/master/docker-compose.yml#L17

**Comment by llitfkitfk** [comment]
I removed the db service from docker compose  file

**Comment by llitfkitfk** [comment]
updated

**Comment by joeblew99** [comment]
ok thanks !!
